# Permalinks
permalink:           pretty

# Setup
title:               Valleybay
tagline:             Raw. Ideas. Thoughts.
url:                 http://valleybay.github.io
paginate:            5
baseurl:             ""
analytics_id:        UA-86543815-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christian Bay
  url:               https://twitter.com/chrisvalleybay

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/valleybay/valleybay.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
